-- MySQL Script generated by MySQL Workbench
-- ter 30 abr 2019 21:16:58 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `ra_usuario` INT NOT NULL AUTO_INCREMENT,
  `fk_id_quarto` INT NOT NULL,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `curso_usuario` VARCHAR(45) NOT NULL,
  `semestre_usuario` INT NOT NULL,
  `email_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ra_usuario`),
  UNIQUE INDEX `ra_usuario_UNIQUE` (`ra_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_projeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tipo_projeto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_projeto` (
  `id_tipo_projeto` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo_projeto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_projeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Area` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Area` (
  `id_area` INT NOT NULL AUTO_INCREMENT,
  `nome_area` VARCHAR(45) NOT NULL,
  `integrantes_area` INT NOT NULL,
  `cor_area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Projeto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Projeto` (
  `id_projeto` INT NOT NULL AUTO_INCREMENT,
  `fk_ra_usuario` INT NOT NULL,
  `fk_id_tipo_projeto` INT NOT NULL,
  `fk_id_area` INT NOT NULL,
  `nome_projeto` VARCHAR(45) NOT NULL,
  `dt_inicio_projeto` DATE NOT NULL,
  `dt_final_projeto` DATE NOT NULL,
  `terminado_projeto` TINYINT NOT NULL,
  `local_projeto` VARCHAR(45) NOT NULL,
  `habilidade_projeto` VARCHAR(250) NOT NULL,
  `descricao_projeto` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`id_projeto`),
  INDEX `fk_id_tipo_projeto_idx` (`fk_id_tipo_projeto` ASC),
  INDEX `fk_id_area_idx` (`fk_id_area` ASC),
  INDEX `fk_ra_usuario_idx` (`fk_ra_usuario` ASC),
  CONSTRAINT `fk_id_tipo_projeto`
    FOREIGN KEY (`fk_id_tipo_projeto`)
    REFERENCES `mydb`.`Tipo_projeto` (`id_tipo_projeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_area_projeto`
    FOREIGN KEY (`fk_id_area`)
    REFERENCES `mydb`.`Area` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ra_usuario_projeto`
    FOREIGN KEY (`fk_ra_usuario`)
    REFERENCES `mydb`.`Usuario` (`ra_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `id_item` INT NOT NULL AUTO_INCREMENT,
  `fk_ra_usuario` INT NOT NULL,
  `nome_item` VARCHAR(45) NOT NULL,
  `top_item` FLOAT NOT NULL,
  `bottom_item` FLOAT NOT NULL,
  `left_item` FLOAT NOT NULL,
  `right_item` FLOAT NOT NULL,
  `imr_url_item` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_item`),
  INDEX `fk_ra_usuario_idx` (`fk_ra_usuario` ASC),
  UNIQUE INDEX `id_item_UNIQUE` (`id_item` ASC),
  CONSTRAINT `fk_ra_usuario_item`
    FOREIGN KEY (`fk_ra_usuario`)
    REFERENCES `mydb`.`Usuario` (`ra_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_informacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tipo_informacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_informacao` (
  `id_tipo_informacao` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo_informacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_informacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Informacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Informacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Informacao` (
  `id_informacao` INT NOT NULL AUTO_INCREMENT,
  `fk_id_tipo_informacao` INT NOT NULL,
  `nome_informacao` VARCHAR(45) NOT NULL,
  `texto_informacao` VARCHAR(450) NOT NULL,
  `local_informacao` VARCHAR(45) NOT NULL,
  `fk_id_area` INT NULL,
  PRIMARY KEY (`id_informacao`),
  INDEX `fk_id_tipo_informacao_idx` (`fk_id_tipo_informacao` ASC),
  INDEX `fk_id_area_idx` (`fk_id_area` ASC),
  CONSTRAINT `fk_id_tipo_informacao`
    FOREIGN KEY (`fk_id_tipo_informacao`)
    REFERENCES `mydb`.`Tipo_informacao` (`id_tipo_informacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_area_informacao`
    FOREIGN KEY (`fk_id_area`)
    REFERENCES `mydb`.`Area` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Achievement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Achievement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Achievement` (
  `id_achievement` INT NOT NULL AUTO_INCREMENT,
  `fk_ra_usuario` INT NOT NULL,
  `nome_achievement` VARCHAR(45) NOT NULL,
  `criterio_achievement` VARCHAR(45) NOT NULL,
  `semestre_achievement` INT NOT NULL,
  PRIMARY KEY (`id_achievement`),
  INDEX `fk_ra_usuario_idx` (`fk_ra_usuario` ASC),
  CONSTRAINT `fk_ra_usuario_achievement`
    FOREIGN KEY (`fk_ra_usuario`)
    REFERENCES `mydb`.`Usuario` (`ra_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
